		new String[]{"Gás glicose", "Urease (URE)", "H2S", "DNAse", "Motilidade (MOT)", "Indol (IND)", "Lisina (LDC)", "Citrato (CIT)", "Malonato (MAL)", "Ornitina (ODC)", "Arginina (ADH)", "Gelatinase", "Fenilalanina (LTD)", "Lactose (LAC)", "Sacarose (SAC)", "Esculina (ESC)"};


		b = new Bacteria("Providencia stuartii");
		b.setProbabilities("Gás glicose",	new double[]{ 0});
		b.setProbabilities("Urease (URE)",	new double[]{ 30});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 10});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 85});
		b.setProbabilities("Indol (IND)",	new double[]{ 98});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 0});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 93});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 0});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 0});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 0});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 95});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 2});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 50});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 0});
		a.add(b);

		b = new Bacteria("Klebsiella aerogenes");
		b.setProbabilities("Gás glicose",	new double[]{ 100});
		b.setProbabilities("Urease (URE)",	new double[]{ 2});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 97});
		b.setProbabilities("Indol (IND)",	new double[]{ 0});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 98});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 95});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 95});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 98});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 0});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 95});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 100});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 98});
		a.add(b);

		b = new Bacteria("Salmonella cholerasuis");
		b.setProbabilities("Gás glicose",	new double[]{ 95});
		b.setProbabilities("Urease (URE)",	new double[]{ 0});
		b.setProbabilities("H2S",	new double[]{ 50});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 95});
		b.setProbabilities("Indol (IND)",	new double[]{ 0});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 95});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 25});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 0});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 100});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 55});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 0});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 0});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 0});
		a.add(b);

		b = new Bacteria("Serratia marcescens");
		b.setProbabilities("Gás glicose",	new double[]{ 55});
		b.setProbabilities("Urease (URE)",	new double[]{ 15});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 98});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 97});
		b.setProbabilities("Indol (IND)",	new double[]{ 1});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 99});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 98});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 3});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 99});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 0});
		b.setProbabilities("Gelatinase",	new double[]{ 90});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 2});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 99});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 95});
		a.add(b);

		b = new Bacteria("Cronobacter sakazakii");
		b.setProbabilities("Gás glicose",	new double[]{ 98});
		b.setProbabilities("Urease (URE)",	new double[]{ 1});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 96});
		b.setProbabilities("Indol (IND)",	new double[]{ 11});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 0});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 99});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 16});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 91});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 99});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 50});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 99});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 100});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 100});
		a.add(b);

		b = new Bacteria("Salmonella pullorum");
		b.setProbabilities("Gás glicose",	new double[]{ 90});
		b.setProbabilities("Urease (URE)",	new double[]{ 0});
		b.setProbabilities("H2S",	new double[]{ 90});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 0});
		b.setProbabilities("Indol (IND)",	new double[]{ 0});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 100});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 0});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 0});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 95});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 10});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 0});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 0});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 0});
		a.add(b);

		b = new Bacteria("Serratia liquefaciens");
		b.setProbabilities("Gás glicose",	new double[]{ 75});
		b.setProbabilities("Urease (URE)",	new double[]{ 3});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 85});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 95});
		b.setProbabilities("Indol (IND)",	new double[]{ 1});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 95});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 90});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 2});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 95});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 0});
		b.setProbabilities("Gelatinase",	new double[]{ 90});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 10});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 98});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 97});
		a.add(b);

		b = new Bacteria("Enterobacter cloacae");
		b.setProbabilities("Gás glicose",	new double[]{ 100});
		b.setProbabilities("Urease (URE)",	new double[]{ 65});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 95});
		b.setProbabilities("Indol (IND)",	new double[]{ 0});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 0});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 100});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 75});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 96});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 97});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 93});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 97});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 30});
		a.add(b);

		b = new Bacteria("Salmonella spp.");
		b.setProbabilities("Gás glicose",	new double[]{ 96});
		b.setProbabilities("Urease (URE)",	new double[]{ 1});
		b.setProbabilities("H2S",	new double[]{ 95});
		b.setProbabilities("DNAse",	new double[]{ 2});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 95});
		b.setProbabilities("Indol (IND)",	new double[]{ 1});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 98});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 95});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 0});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 97});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 70});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 1});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 1});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 5});
		a.add(b);

		b = new Bacteria("Serratia rubidae");
		b.setProbabilities("Gás glicose",	new double[]{ 30});
		b.setProbabilities("Urease (URE)",	new double[]{ 2});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 99});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 85});
		b.setProbabilities("Indol (IND)",	new double[]{ 0});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 55});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 95});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 94});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 0});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 0});
		b.setProbabilities("Gelatinase",	new double[]{ 90});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 100});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 99});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 94});
		a.add(b);

		b = new Bacteria("Klebsiella ozaenae");
		b.setProbabilities("Gás glicose",	new double[]{ 50});
		b.setProbabilities("Urease (URE)",	new double[]{ 10});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 0});
		b.setProbabilities("Indol (IND)",	new double[]{ 0});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 40});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 30});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 3});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 3});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 6});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 30});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 20});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 80});
		a.add(b);

		b = new Bacteria("Proteus vulgaris");
		b.setProbabilities("Gás glicose",	new double[]{ 85});
		b.setProbabilities("Urease (URE)",	new double[]{ 95});
		b.setProbabilities("H2S",	new double[]{ 95});
		b.setProbabilities("DNAse",	new double[]{ 80});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 95});
		b.setProbabilities("Indol (IND)",	new double[]{ 98});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 0});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 15});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 0});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 0});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 0});
		b.setProbabilities("Gelatinase",	new double[]{ 91});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 99});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 2});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 97});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 50});
		a.add(b);

		b = new Bacteria("Hafnia alvei");
		b.setProbabilities("Gás glicose",	new double[]{ 98});
		b.setProbabilities("Urease (URE)",	new double[]{ 4});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 85});
		b.setProbabilities("Indol (IND)",	new double[]{ 0});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 100});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 10});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 50});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 98});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 6});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 5});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 10});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 7});
		a.add(b);

		b = new Bacteria("Proteus mirabilis");
		b.setProbabilities("Gás glicose",	new double[]{ 96});
		b.setProbabilities("Urease (URE)",	new double[]{ 98});
		b.setProbabilities("H2S",	new double[]{ 98});
		b.setProbabilities("DNAse",	new double[]{ 50});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 95});
		b.setProbabilities("Indol (IND)",	new double[]{ 2});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 0});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 65});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 2});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 99});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 0});
		b.setProbabilities("Gelatinase",	new double[]{ 90});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 98});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 2});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 15});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 0});
		a.add(b);

		b = new Bacteria("Salmonella paratyphi A");
		b.setProbabilities("Gás glicose",	new double[]{ 99});
		b.setProbabilities("Urease (URE)",	new double[]{ 0});
		b.setProbabilities("H2S",	new double[]{ 10});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 95});
		b.setProbabilities("Indol (IND)",	new double[]{ 0});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 0});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 0});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 0});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 95});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 15});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 0});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 0});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 0});
		a.add(b);

		b = new Bacteria("Shigella boydii");
		b.setProbabilities("Gás glicose",	new double[]{ 0});
		b.setProbabilities("Urease (URE)",	new double[]{ 0});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 0});
		b.setProbabilities("Indol (IND)",	new double[]{ 25});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 0});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 0});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 0});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 2});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 18});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 1});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 0});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 0});
		a.add(b);

		b = new Bacteria("Enterobacter gergoviae");
		b.setProbabilities("Gás glicose",	new double[]{ 98});
		b.setProbabilities("Urease (URE)",	new double[]{ 93});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 90});
		b.setProbabilities("Indol (IND)",	new double[]{ 0});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 90});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 99});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 96});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 100});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 0});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 55});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 98});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 97});
		a.add(b);

		b = new Bacteria("Salmonella outras");
		b.setProbabilities("Gás glicose",	new double[]{ 100});
		b.setProbabilities("Urease (URE)",	new double[]{ 0});
		b.setProbabilities("H2S",	new double[]{ 100});
		b.setProbabilities("DNAse",	new double[]{ 1});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 99});
		b.setProbabilities("Indol (IND)",	new double[]{ 1});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 99});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 90});
		b.setProbabilities("Malonato (MAL)",	null);
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 99});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 70});
		b.setProbabilities("Gelatinase",	new double[]{ 1});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	null);
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 1});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 0,  15});
		a.add(b);

		b = new Bacteria("Edwardsiella tarda");
		b.setProbabilities("Gás glicose",	new double[]{ 100});
		b.setProbabilities("Urease (URE)",	new double[]{ 0});
		b.setProbabilities("H2S",	new double[]{ 100});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 98});
		b.setProbabilities("Indol (IND)",	new double[]{ 99});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 100});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 1});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 0});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 100});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 0});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 0});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 0});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 0});
		a.add(b);

		b = new Bacteria("Providencia rettgeri");
		b.setProbabilities("Gás glicose",	new double[]{ 10});
		b.setProbabilities("Urease (URE)",	new double[]{ 98});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 94});
		b.setProbabilities("Indol (IND)",	new double[]{ 99});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 0});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 95});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 0});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 0});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 0});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 98});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 5});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 15});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 35});
		a.add(b);

		b = new Bacteria("Klebsiella pneumoniae");
		b.setProbabilities("Gás glicose",	new double[]{ 97});
		b.setProbabilities("Urease (URE)",	new double[]{ 95});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 0});
		b.setProbabilities("Indol (IND)",	new double[]{ 0});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 98});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 98});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 93});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 0});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 0});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 98});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 99});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 99});
		a.add(b);

		b = new Bacteria("Shigella sonnei");
		b.setProbabilities("Gás glicose",	new double[]{ 0});
		b.setProbabilities("Urease (URE)",	new double[]{ 0});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 0});
		b.setProbabilities("Indol (IND)",	new double[]{ 0});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 0});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 0});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 0});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 98});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 2});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 2});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 1});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 0});
		a.add(b);

		b = new Bacteria("Shigella flexneri");
		b.setProbabilities("Gás glicose",	new double[]{ 3});
		b.setProbabilities("Urease (URE)",	new double[]{ 0});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 0});
		b.setProbabilities("Indol (IND)",	new double[]{ 50});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 0});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 0});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 0});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 0});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 5});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 1});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 1});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 0});
		a.add(b);

		b = new Bacteria("Citrobacter freundii");
		b.setProbabilities("Gás glicose",	new double[]{ 89});
		b.setProbabilities("Urease (URE)",	new double[]{ 44});
		b.setProbabilities("H2S",	new double[]{ 78});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 89});
		b.setProbabilities("Indol (IND)",	new double[]{ 33});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 0});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 78});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 11});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 0});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 67});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 78});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 89});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 0});
		a.add(b);

		b = new Bacteria("Klebsiella rhinoscleromatis");
		b.setProbabilities("Gás glicose",	new double[]{ 0});
		b.setProbabilities("Urease (URE)",	new double[]{ 0});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 0});
		b.setProbabilities("Indol (IND)",	new double[]{ 0});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 0});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 0});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 95});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 0});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 0});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 0});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 75});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 30});
		a.add(b);

		b = new Bacteria("Eschenchia coli inativa");
		b.setProbabilities("Gás glicose",	new double[]{ 5});
		b.setProbabilities("Urease (URE)",	new double[]{ 1});
		b.setProbabilities("H2S",	new double[]{ 1});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 95});
		b.setProbabilities("Indol (IND)",	new double[]{ 98});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 90});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 1});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 0});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 65});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 17});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 25});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 15});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 5});
		a.add(b);

		b = new Bacteria("Eschenchia coli");
		b.setProbabilities("Gás glicose",	new double[]{ 95});
		b.setProbabilities("Urease (URE)",	new double[]{ 1});
		b.setProbabilities("H2S",	new double[]{ 1});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 95});
		b.setProbabilities("Indol (IND)",	new double[]{ 98});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 90});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 1});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 0});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 65});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 17});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 95});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 50});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 35});
		a.add(b);

		b = new Bacteria("Citrobacter diversus (kosen)");
		b.setProbabilities("Gás glicose",	new double[]{ 98});
		b.setProbabilities("Urease (URE)",	new double[]{ 75});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 95});
		b.setProbabilities("Indol (IND)",	new double[]{ 99});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 0});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 99});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 95});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 99});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 80});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 50});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 40});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 1});
		a.add(b);

		b = new Bacteria("Shigella dysenteriae");
		b.setProbabilities("Gás glicose",	new double[]{ 0});
		b.setProbabilities("Urease (URE)",	new double[]{ 0});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 0});
		b.setProbabilities("Indol (IND)",	new double[]{ 45});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 0});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 0});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 0});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 0});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 2});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 0});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 0});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 0});
		a.add(b);

		b = new Bacteria("Yersinia enterocolitica");
		b.setProbabilities("Gás glicose",	new double[]{ 5});
		b.setProbabilities("Urease (URE)",	new double[]{ 75});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 5});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 2});
		b.setProbabilities("Indol (IND)",	new double[]{ 50});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 0});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 0});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 0});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 95});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 0});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 5});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 95});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 25});
		a.add(b);

		b = new Bacteria("Salmonella gallinarum");
		b.setProbabilities("Gás glicose",	new double[]{ 0});
		b.setProbabilities("Urease (URE)",	new double[]{ 0});
		b.setProbabilities("H2S",	new double[]{ 100});
		b.setProbabilities("DNAse",	new double[]{ 10});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 0});
		b.setProbabilities("Indol (IND)",	new double[]{ 0});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 90});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 0});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 0});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 1});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 10});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 0});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 0});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 0});
		a.add(b);

		b = new Bacteria("Citrobacter amalonaticus");
		b.setProbabilities("Gás glicose",	new double[]{ 97});
		b.setProbabilities("Urease (URE)",	new double[]{ 85});
		b.setProbabilities("H2S",	new double[]{ 5});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 95});
		b.setProbabilities("Indol (IND)",	new double[]{ 100});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 0});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 95});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 1});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 95});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 85});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 35});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 9});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 5});
		a.add(b);

		b = new Bacteria("Pantoea agglomerans");
		b.setProbabilities("Gás glicose",	new double[]{ 20});
		b.setProbabilities("Urease (URE)",	new double[]{ 20});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 85});
		b.setProbabilities("Indol (IND)",	new double[]{ 20});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 0});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 50});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 65});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 0});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 0});
		b.setProbabilities("Gelatinase",	new double[]{ 2});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 20});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 40});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 75});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 60});
		a.add(b);

		b = new Bacteria("Salmonella typhi");
		b.setProbabilities("Gás glicose",	new double[]{ 0});
		b.setProbabilities("Urease (URE)",	new double[]{ 0});
		b.setProbabilities("H2S",	new double[]{ 97});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 97});
		b.setProbabilities("Indol (IND)",	new double[]{ 0});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 98});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 0});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 0});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 0});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 3});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 0});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 1});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 0});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 0});
		a.add(b);

		b = new Bacteria("Klebsiella oxytoca");
		b.setProbabilities("Gás glicose",	new double[]{ 97});
		b.setProbabilities("Urease (URE)",	new double[]{ 90});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 0});
		b.setProbabilities("Indol (IND)",	new double[]{ 99});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 99});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 95});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 98});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 0});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 0});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 1});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 100});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 100});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 100});
		a.add(b);

		b = new Bacteria("Morganella morganii");
		b.setProbabilities("Gás glicose",	new double[]{ 90});
		b.setProbabilities("Urease (URE)",	new double[]{ 95});
		b.setProbabilities("H2S",	new double[]{ 20});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	null);
		b.setProbabilities("Indol (IND)",	new double[]{ 95});
		b.setProbabilities("Lisina (LDC)",	null);
		b.setProbabilities("Citrato (CIT)",	new double[]{ 0});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 1});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 95});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 0});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 95});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 1});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 0});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 0});
		a.add(b);

		b = new Bacteria("Providencia alcalifaciens");
		b.setProbabilities("Gás glicose",	new double[]{ 85});
		b.setProbabilities("Urease (URE)",	new double[]{ 0});
		b.setProbabilities("H2S",	new double[]{ 0});
		b.setProbabilities("DNAse",	new double[]{ 0});
		b.setProbabilities("Motilidade (MOT)",	new double[]{ 96});
		b.setProbabilities("Indol (IND)",	new double[]{ 99});
		b.setProbabilities("Lisina (LDC)",	new double[]{ 0});
		b.setProbabilities("Citrato (CIT)",	new double[]{ 98});
		b.setProbabilities("Malonato (MAL)",	new double[]{ 0});
		b.setProbabilities("Ornitina (ODC)",	new double[]{ 0});
		b.setProbabilities("Arginina (ADH)",	new double[]{ 0});
		b.setProbabilities("Gelatinase",	new double[]{ 0});
		b.setProbabilities("Fenilalanina (LTD)",	new double[]{ 98});
		b.setProbabilities("Lactose (LAC)",	new double[]{ 0});
		b.setProbabilities("Sacarose (SAC)",	new double[]{ 15});
		b.setProbabilities("Esculina (ESC)",	new double[]{ 0});
		a.add(b);
